before:
  hooks:
    - docker login -u {{ .Env.DOCKER_USERNAME }} -p {{ .Env.DOCKER_TOKEN }}

builds:
  - main: ./cmd/server
    id: "jsonshredder"
    env:
      - CGO_ENABLED=0
    binary: jsonshredder
    goos:
      - linux
      - darwin
      - windows

archives:
- format_overrides:
  - goos: windows
    format: zip
    

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:

  prerelease: auto

dockers:
  -
    goos: linux

    goarch: amd64

    ids:
    - jsonshredder

    image_templates:
    - "wakumaku/jsonshredder:latest"
    - "wakumaku/jsonshredder:{{ .Tag }}"
    - "wakumaku/jsonshredder:v{{ .Major }}"

    dockerfile: ./build/Dockerfile.goreleaser
