name: tests

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      -
        name: Run Tests
        run: |
          export AWS_CONFIG_FILE=${GITHUB_WORKSPACE}/dev/.aws/config
          export AWS_SHARED_CREDENTIALS_FILE=${GITHUB_WORKSPACE}/dev/.aws/credentials
          go test ./... -bench=. -v --cover --race
          